### ISSUE TITLE
Segmentation fault on Macos

### ISSUE THREAD

**Issue by tmseiler** [HaliteChallenge/Halite-III#58] opened 2018-10-20 15:24 UTC
This is hard for me to verify, but I was getting a string of these segfaults this morning. They seemed to happen immediately after statements like this:

`
[warn] [31] [P1] entity 0 was directed to use 1 halite to move west, but only 0 halite was available
[warn] [31] [P0] entity 1 was directed to use 1 halite to move east, but only 0 halite was available
[warn] [31] [P0] owned entities 5, 1 collided on cell (9, 16) as the result of moves on this turn
[warn] [31] [P1] owned entities 4, 0 collided on cell (22, 16) as the result of moves on this turn
run_game.sh: line 6: 18498 Segmentation fault: 11  ./halite --replay-directory replays/ -vvv --width 32 --height 32 "java -jar build/libs/halite3-6.jar" "java -jar build/libs/halite3-6.jar"
`

I added some more protection around fuel management, and the errors went away.

**Comment by snaar** [comment] 2018-10-20 15:50
Can you by any chance email the copy of the bot that reproduces the segfault to halite@halite.io?

**Comment by tmseiler** [comment] 2018-10-20 16:15
Done. FYI -- my latest verison doesn't collide or run out of fuel, and it's still segfaulting.

**Comment by lidavidm** [comment] 2018-10-20 16:58
I believe this is a duplicate of #22, after investigating.

**Comment by tmseiler** [comment] 2018-10-20 19:06
Thanks, that helps a lot to at least work around on my end.

**Closed** 2018-10-20 19:51 UTC
